# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170428_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
